version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
